### PR TITLE
Update gs_info_wlr.R

### PR DESCRIPTION
**Pull request by elong0527**
address warning reported in https://github.com/Merck/gsDesign2/issues/28

### CODE REVIEW

**Comment by LittleBeannie** [comment]
Hi Yilong, could you please update Merck/gsDesign2 in the future? Since gsdmvn will be retired soon...

**Comment by elong0527** [comment]
yes, I realized that and updated gsDesign2 in a PR.

**Comment by nanxstats** [comment]
Should we retire (archive) this repo then? Maybe a good item for discussion.

**Comment by nanxstats** [comment]
I'm closing this PR as we have merged gsdmvn into gsDesign2 for a while and we are archiving this repo. This particular issue will be resolved (or has already been resolved) in gsDesign2.

**Pull request closed without merging**
